name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"  # Ne déclenche le workflow que si le dossier backend change

env:
  REG_NAME: "acrfi21210.azurecr.io"      # Remplace par le nom réel de ton registry Azure
  IMAGE_NAME: "todo-backend-dla:latest"      # Nom de ton image Docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # -------------------------
      # Checkout du repo
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------
      # Login à la registry Docker (ACR)
      # -------------------------
      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ env.REG_NAME }}.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USER }}-dla --password-stdin

      # -------------------------
      # Build Docker image
      # -------------------------
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REG_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} ./backend

      # -------------------------
      # Push Docker image
      # -------------------------
      - name: Push Docker image to registry
        run: |
          docker push ${{ env.REG_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
